### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Estreex** [pycsgo/pycsgo#2]
help me i'm a download all modules phyton.

Python 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

Traceback (most recent call last):
  File "C:\Users\Estreex72\Desktop\Camatos\Main.py", line 2, in <module>
    from memorpy import*
  File "C:\Python27\lib\site-packages\memorpy\__init__.py", line 26, in <module>
    from MemWorker import*
  File "C:\Python27\lib\site-packages\memorpy\MemWorker.py", line 20, in <module>
    import Process
  File "C:\Python27\lib\site-packages\memorpy\Process.py", line 5, in <module>
    from BaseProcess import *
  File "C:\Python27\lib\site-packages\memorpy\BaseProcess.py", line 162, in <module>
    class ProcessException(Exception):
  File "C:\Python27\lib\site-packages\memorpy\BaseProcess.py", line 163, in ProcessException
    junk()
  File "C:\Python27\lib\site-packages\memorpy\BaseProcess.py", line 17, in junk
    while x is False:
UnboundLocalError: local variable 'x' referenced before assignment
>>>

**Comment by FloydRepo** [comment]
uh don't bother with it
it's been patched
